### PR TITLE
Use Composer.currentMarker and Composer.endToMarker to avoid wrapping in Maybe

### PR DESCRIPTION
**Pull request by kyay10**
This is the same internal mechanism used by Compose for non-local returns.

This removes all unnecessary usages of Maybe, bind, and the controlFlowSafe functions since they're no longer needed. It also removes the separation of effect's state and its invocation.

I'm cautious about merging this because it uses a Compose internal API.

### CODE REVIEW

**Comment by nomisRev** [comment]
> I'm cautious about merging this because it uses a Compose internal API.

Did you get in contact with them concerning making this public, or "delicate"?

**Comment by kyay10** [comment]
@nomisRev I should, just wasn't sure who to contact.
To clarify, the APIs I'm using (`currentMarker` and `endToMarker`) are `public`, but their docs say `Compose compiler plugin API. DO NOT call directly.`

In fact, this seems to be reusable in a manner exactly like `runCatching`:
```kotlin
@Composable
internal inline fun <R> runCatchingComposable(block: @Composable () -> R): Result<R> {
  val marker = currentComposer.currentMarker
  return tryCatch({ Result.success(block()) }) {
    currentComposer.endToMarker(marker)
    Result.failure(it)
  }
}

// Used to prevent ILLEGAL_TRY_CATCH_AROUND_COMPOSABLE
private inline fun <R> tryCatch(block: () -> R, onError: (Throwable) -> R): R = try {
  block()
} catch (e: Throwable) {
  onError(e)
}
```
Theoretically, it can be added to the Compose runtime utils themselves, which would be of great value. Also, it could be transformed automatically whenever there's a try-catch around a `Composable` (right now that makes the compiler throw an error). I think the best situation is if they can either add `runCatchingComposable` to their lib or if they can auto-transform `try-catch` around `Composable`s to use the marker methods (while handling `inline` funs gracefully so that Raise builders can work too). They can also just mark the APIs delicate, and that'd be good enough for this project.

**Comment by nomisRev** [comment]
It's wise to keep as much as possible as "internal/private", but sometimes it's because they don't know of other good use-cases. So reaching out lets them know what this use-case would be using it for (maybe we find out some gotchas).

To me it sounds like `try/catch` should be allowed, especially if it can be fixed like this but I don't know enough of the Compose internals for that.


> Minor issue: if your function returns Unit, it *must* be marked with @NonRestartableComposable

🤯 okay, compose does weird stuff 😁

**Comment by nomisRev** [comment]
> Compose skips the composition of composables that return Unit and have no out-of-date dependencies (well it's slightly more complicated but that's a good enough approximation).

Oh, I see since they assume a `@Composeable` of `Unit` does nothing? Or rather, just return a "widget"(?).
And a "side-effect" should otherwise be build by `Effect` using a 'key', right?

Sorry, like I said little experience with Compose. I knew my FOMO was telling me something 🤣

**Comment by kyay10** [comment]
They assume a Composable returning unit "emits a Node in the Tree implied by composition" in Compose Lingo, as in they assume it only adds things onto the UI, and hence reuse the nodes ("widgets" or whatever) it added. A "side-effect" should likely be build by `SideEffect` which schedules a block to be ran only if the composition is successful (Compose can cancel Composition if e.g. layouting happens but then data changes, so the layout gets thrown away and doesn't get drawn). Theoretically, they'd like to be able to run Compositions on background threads eventually.
The way I run the `shift` block is that I use a `LaunchedEffect`, which is the recommended way to start a coroutine that should span multiple compositions. I use a tiny hack to restart that coroutine when I want by using a key with custom equality. If that hack ever fails, it's no problem since I can just add an extra var to `Shift` like `var restartSignal: Boolean` and flip it when I want to restart the coroutine. I didn't want to add unnecessary state though, hence the hack, but arguably it's a premature optimization. Another way to do it, which can be good for debugging purposes, is to have a `var restartNumber: Int = 0` and only ever increment it.
The issue is when someone creates a function that uses `shift` and returns Unit, Compose assumes it can thus skip it if it wants to. There's probably something I can do with `MutableState` and whatnot, but for now the annotation is simple enough.

**Comment by nomisRev** [comment]
Thanks for the explanation @kyay10! Makes much more sense to me. I think Compose very closely mimics what I want to build, which is kind-of like an effectful streaming tree data structure.

Where `Flow` is like `List`, 'this' is like `Tree` which sounds exactly like what Compose is doing because with an effectful tree like this you need to be able to restart, and cancel operations in certain parts of the tree.

**Comment by nomisRev** [comment]
Merged 👀

any updates to share? 😬

**Comment by kyay10** [comment]
@nomisRev check out #2 ! I need to write a way longer description, but for now the tests should showcase everything pretty well! I explained a bit on Slack in the discussion thread about this.

**Pull request merged**
